### ISSUE TITLE
#US01 Clonar repositorio en local y crear rama propia

### ISSUE THREAD

**Issue by tefsantana** [tefsantana/ISPC-Fullstack-KillCode#1]
### Criterios
1. Como programador/estudiante quiero clonar el repositorio de manera local para poder trabajar en conjunto en base al código, al aproximarse un proyecto.
2. Como programador/estudiante quiero crear una rama propia para subir mis cambios.

- [x] #Integrante: Estefanía Santana
- [x] #Integrante: Romina Herrera 
- [x] #Integrante: Mario Daniel Ledesma
- [x] #Integrante: Nicolás Ezequiel Lerda
- [x] #Integrante: Leonardo Cuestas Manthai 
- [x] #Integrante: Jimena Lorena Galleguillo 
- [x] #Integrante: Facundo Nahuel Cascallares Martínez
- [x] #Integrante: Ignacio Carnero
- [ ] #Integrante: Mercedes Vilaseca

**Comment by MDLDeveloper** [comment]
Cumplido

**Comment by Romherre** [comment]
Tarea Lista

**Comment by Leoo10** [comment]
Cumplí vamos nomás jajajaj

**Comment by Nicolaslerda** [comment]
Task accomplished

**Comment by tefsantana** [comment]
Cierro historia ya que todos los participantes **activos** terminamos la tarea.
